<div class="content mt-3">
	<div class="container">
    	<div class="row">
			<div class="col-md-12 col-12 col-xl-12 com-sm-12 col-lg-12 contents">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-6 justify-content-center p-4">
					<div class="mb-4">
						<h2 class="text-center text-danger"><i class="fa fa-lock"></i></h2>
						<h3 class="text-center mb-3" style="font-weight: bolder;">Entrar no sistema</h3>
					</div>
					<hr>
					<div id="mensagem"></div>
					<?= $this->session->has('acesso_negado') ? '<p class="alert alert-danger text-center" id="p-acesso-negado">'.$this->session->get('acesso_negado').'</p>' : '' ?>
					<form method="POST">
						<div class="form-group">
							<label for="email">E-mail: <sup class="text-danger">*</sup></label>
							<input type="text" name="email" id="email" class="form-control" placeholder="Digite seu e-mail">
							<div class="invalid-feedback text-center">
								
							</div>
						</div>

						<div class="form-group">
							<label for="senha">Senha: <sup class="text-danger">*</sup><span id="ver-senha" style="font-size: 20px;"><i class="fa fa-eye"></i></span></label>
							<input type="password" name="senha" id="senha" class="form-control" placeholder="Digite sua senha">
						</div>

						<button type="button" class="btn btn-block btn-primary" style="background: #0d457e;" id="btn-login">Entrar</button>
						<div class="col-md-12 mt-2 text-center">
							<a class="text-primary" href="signup"><p>Não tem uma conta? Cadastre-se!</p></a>
						</div>
					</form>
				</div>
				</div>
				</div>
				<!-- <div class="col-md-4 col-sm-4 col-xl-4 m-auto">
					<img src="<?//= BASE_URL . '/img/background-ico.png' ?>" alt="Plano de fundo" class="img-fluid logo">
				</div> -->
			</div>
    	</div>
  	</div>
</div>
<script src="<?= BASE_URL . '/js/forms/form-login.js' ?>"></script>

<script>
	$(document).ready(function() {
		// console.log($('#p-acesso-negado'));
		// console.log($('#mensagem').html());
		$('#btn-login').on('click', () => {
			$('#p-acesso-negado').hide();
		})
		
	});
</script>
<?php if($this->session->has('acesso_negado')): ?>
	<?php $this->session->remove('acesso_negado') ?>;
<?php endif; ?>