<div class="content mt-3">
	<div class="container">
    	<div class="row">
			<div class="col-md-12 col-12 col-xl-12 com-sm-12 col-lg-12 contents">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-6 justify-content-center p-4">
					<div class="mb-4">
						<h2 class="text-center text-danger"><i class="fa fa-lock"></i></h2>
						<h3 class="text-center mb-3" style="font-weight: bolder;">Entrar no sistema</h3>
					</div>
					<hr>
					<br>
						<p class="<isset($login_invalido) ? 'alert alert-danger text-center' : ''?>"><?=$login_invalido ?? ''?></p>
					<form action="<site_url('usuario/login')?>" method="POST">
						<div class="form-group">
							<label for="email">E-mail: <sup class="text-danger">*</sup></label>
							<input type="text" name="email" id="email" class="form-control <?= isset($email_erro) ? 'is-invalid' : '' ?>" value="<?= $email ?? '' ?>" placeholder="Digite seu e-mail">
							<div class="invalid-feedback text-center">
								<?= $email_erro ?? '' ?>
							</div>
						</div>

						<div class="form-group">
							<label for="senha">Senha: <sup class="text-danger">*</sup></label>
							<input type="password" name="senha" id="senha" class="form-control <?= isset($senha_erro) ? 'is-invalid' : '' ?>" value="<?= $senha ?? '' ?>" placeholder="Digite sua senha">
							<div class="invalid-feedback text-center">
								<?= $senha_erro ?? '' ?>
							</div>
						</div>

						<button type="submit" class="btn btn-block btn-primary" style="background: #0d457e;" onclick="enviar_dados_login()">Entrar</button>
						<div class="col-md-12 mt-2 text-center">
							<a class="text-primary" href="signup"><p>Não tem uma conta? Cadastre-se!</p></a>
						</div>
					</form>
				</div>
				</div>
				
				</div>
				<!-- <div class="col-md-4 col-sm-4 col-xl-4 m-auto">
					<img src="<base_url('assets/images/background-ico.png')?>" alt="Plano de fundo" class="img-fluid logo">
				</div> -->
			</div>
    	</div>
  	</div>
</div>