<div class="container pt-3 mt-3">
    <div class="row">
        <div class="col-sm-12 col-12 col-md-10 col-xl-8 col-lg-8 m-auto">
            <div class="card p-3 text-center" style="background-color: #ccc;">
                  <a href="<?= BASE_URL ?>" class="mb-2">Voltar à página inicial</a>

                <div class="col-12 col-md-12 col-lg-12 col-sm-12 mt-2 mb-2 m-auto pr-3 pl-3 pb-2 pt-2">
                  <a class="btn btn-sm btn-outline-primary ml-0 float-left" href="<?= BASE_URL . '/usuario/perfil/editar' ?>"><i class="fa fa-pencil ml-2 mr-2"></i>Editar perfil</a>
                  <a class="btn btn-sm btn-outline-danger float-right mr-2" href="<?= BASE_URL . '/usuario/perfil/excluir' ?>"><i class="fa fa-times ml-2 mr-0"></i> Excluir perfil</a>
               </div>
               <div class="card-body mb-2 fa" style="background-color: #eee;">
                <img class="img-fluid rounded-circle mb-2" src="<?= BASE_URL . '/img/usuarios/perfil/' . $this->session->get('id_usuario').'.jpg' ?>" style="width: 128px; height:128px">
               <div class="card-text">
                     <label for="nome"><i class="fa fa-user mr-2"></i>Nome de usuário:</label>
                     <h3 class="form-control mb-4"><?=$this->session->usuario?></h3>
                     <h3></i></h3>
                     <label for="nome"><i class="fa fa-envelope mr-2"></i> Endereço de e-mail:</label>
                     <h3 class="form-control mb-4"><?=$this->session->email?></h3>
               </div>
            </div>
            </div>
        </div>
    </div>
</div>