<div class="content mt-3">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-12 col-xl-12 com-sm-12 col-lg-12 contents m-auto">
				<div class="row justify-content-center">
					<div class="col-12 col-lg-6 justify-content-center p-4">
						<div class="mb-4">
							<h4 class="text-center text-primary"><i class="fa fa-user-plus"></i></h4>
							<h3 class="text-center" style="font-weight: bolder;">Criar uma conta</h3>
						</div>
						<hr>
						<div id="mensagem"></div>
						<form id="frm-signup" method="POST">
							<div class="form-group">
								<label for="nome">Nome: <sup class="text-danger">*</sup></label>
								<input type="text" name="nome" id="nome"
									class="form-control"
									value="" placeholder="Digite seu nome">
								<div class="invalid-feedback text-center m-auto" id="nome-erro">
									
								</div>
							</div>

							<div class="form-group">
								<label for="email">E-mail: <sup class="text-danger">*</sup></label>
								<input type="text" name="email" id="email"
									class="form-control "
									value="" placeholder="Digite seu e-mail">
								<div class="invalid-feedback text-center m-auto" id="email-erro">
									
								</div>
							</div>

							<div class="form-group">
								<label for="senha">Senha: <sup class="text-danger">*&nbsp;</sup><span id="ver-senha" style="font-size: 20px;"><i class="fa fa-eye"></i></span></label>
								<input type="password" name="senha" id="senha"
									class="form-control "
									value="" placeholder="Crie uma senha">
								<div class="invalid-feedback text-center m-auto" id="senha-erro">
									
								</div>
							</div>

							<div class="form-group">
								<label for="confirm_senha">Confirme a senha: <sup class="text-danger">*&nbsp;</sup><span id="ver-confirm-senha" style="font-size: 20px;"><i class="fa fa-eye"></i></span></label>
								<input type="password" name="confirm_senha" id="confirm-senha"
									class="form-control "
									value="" placeholder="Confirme sua senha">
								<div class="invalid-feedback text-center m-auto" id="confirm-senha-erro">
									
								</div>
							</div>

							<button type="button" id="btn-signup" class="btn btn-block btn-primary"
								style="background: #0d457e;">Cadastrar</button>

							<div class="col-md-12 mt-2 text-center">
								<a class="text-primary" href="<?= BASE_URL . '/usuario/login' ?>">
									<p>Tem uma conta? Faça login!</p>
								</a>
							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

<script src="<?=BASE_URL . '/js/forms/form-signup.js' ?>"></script>
