<?php /*if(isset($_SESSION['signup_sucesso'])):*/ if($this->session->has('signup_sucesso')): ?>
<div class="container p-5">
    <div class="col-sm-12 col-md-12 col-xl-12 m-auto text-center">
    <a href="<?= BASE_URL ?>" style="font-weight: bolder; font-size: 16pt;">Web-Store
		<img src="<?= BASE_URL . '/img/background-ico.png' ?>" alt="Plano de fundo" class="img-fluid logo">
	</a>
    </div>
    <h5 class="alert alert-success text-center mt-5"><?= $this->session->get('signup_sucesso'); ?></h5>
    <hr>
        <div class="m-auto">
            
            <div class="text-center mt-2 col-6 col-xl-4 col-md-4 col-sm-6 col-lg-4 m-auto">
                <a class="btn btn-outline-primary btn-block" href="<?= BASE_URL ?>">Página inicial</a>
                <br>
                <a class="btn btn-outline-success btn-block" href="login">Fazer login <i class="fa fa-sign-in"></i></a>
            </div>
        </div>
    <!-- </div> -->
</div>
<?php session_destroy(); ?>
<?php endif; ?>