<?php if($allUsers): ?>
    <div class="container mt-5 p-3">
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-8 p-3 m-auto text-center">
                <h3>Lista de usuarios</h3>
                <hr>
            </div>
        </div>
        <div class="col-xl-8 col-lg-8 col-12 m-auto">
            <input class="form-control float-center" type="search" id="user-search" placeholder="Pesquisar usuário">
        </div>

        <div class="col-xl-8 col-lg-8 col-12 pt-3 pb-5 m-auto">
            <table class="table table-striped table-hover">
                <div class="thead-dark">
                    <thead class="bg-dark text-light">
                        <tr>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Total de vendas</th>
                        </tr>
                    </thead>
                    <tbody style="background-color: rgb(225, 225, 225); cursor: pointer" id="user-list">
                        
                    </tbody>
                </div>
            </table>
        </div>
    </div>
    <script src="<?= BASE_URL . '/js/pesquisar-usuario.js' ?>"></script>
<?php else: ?>
    <?php var_dump($dados); ?>
    aa
<?php endif; ?>