<div class="">
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="<?= BASE_URL . '/img/slide/img-1.jpeg' ?>" alt=""">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>Primeiro</h5>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque modi, delectus molestias numquam vitae eaque aliquid ex quo magnam, minima nihil temporibus nostrum dignissimos illum cumque earum? Qui, rem accusantium?</p> -->
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="<?= BASE_URL . '/img/slide/img-2.jpeg' ?>" alt="">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>Primeiro</h5>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque modi, delectus molestias numquam vitae eaque aliquid ex quo magnam, minima nihil temporibus nostrum dignissimos illum cumque earum? Qui, rem accusantium?</p> -->
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="<?= BASE_URL . '/img/slide/img-3.jpeg' ?>" alt="">
                <div class="carousel-caption d-none d-md-block">
                    <!-- <h5>Primeiro</h5>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque modi, delectus molestias numquam vitae eaque aliquid ex quo magnam, minima nihil temporibus nostrum dignissimos illum cumque earum? Qui, rem accusantium?</p> -->
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Próximo</span>
        </a>

    </div>
</div>

<div class="page-header mt-0 m-auto py-2 text-center position-relative">
    <div class="container">
        <br>
        <ul class="list-group list-group-flush text-center">
            <h4>Já tem uma conta?</h4><a href="usuario/login">Fazer login</a>
            <hr>
            <h4>Não tem uma conta?</h4><a href="usuario/signup">Criar conta</a>
        </ul>

        <br>
        <br>
        <hr>
        <div class="row">
            <div class="col-12 m-auto">
                <small>Sistema desenvolvido por <a href="pagina/sobre">Daniel Pereira Sanches <img
                            class="rounded-circle img-fluid ml-2" src="<?= BASE_URL . '/img/icons/dev/dev-icon.jpg' ?>"
                            alt="" style="width: 30px; height: 30px;"></a></small>
            </div>
        </div>
        <hr>
    </div>
</div>