<style>
    .btn-responder{
        background-color: #ccc;
        color: black;
        font-weight: bolder;
    }
</style>
<div class="container-fluid" style="position: relative;">
    <div class="col-sm-12 col-xl-8 col-xs-12 col-md-12 col-lg-12 m-auto">
        <div class="card pb-2 pt-4">
            <div class="card-header text-center text-light bg-dark">
                <h6>Acerte as perguntas abaixo para ganhar dinheiro</h6>
            </div>
            <div style="background-color: blanchedalmond;">
                <p class="pl-2 ml-2 mr-3" style="font-size: 9pt;"><strong id="perguntas-feitas"></strong></p>
                <div class="row m-auto">
                    <p class="pl-2 text-success" style="font-size: 9pt;"><strong id="perguntas-resp-correta"></strong></p>
                    <p class="pl-2 text-danger mr-5" style="font-size: 9pt;"><strong id="erros"></strong></p>
                    
                    <!--<span class="pl-2 text-dark" style="font-size: 9pt; font-weight: bold;">Saldo ganho: <strong id="saldo-ganho" class="text-success"></strong></span>-->
                </div>
                <p class="pl-2 ml-2 text-dark" style="font-size: 9pt;font-weight: bold;">Saldo na conta: <strong id="saldo-na-conta"></strong></p>
            </div>
            <div class="card-body pb-5 pt-2">
                <form method="POST" class="">
                    <h6 class="text-center" style="font-family: Arial, Helvetica, sans-serif; font-size: 10pt;">Valor da pergunta: <strong id="valor-pergunta" class="text-success"></strong></h6>
                    <hr>
                    <div class="form-group">
                        <h5 class="text-left form-control-xl text-center mt-1 mb-3" id="pergunta">Pergunta</h5>
                        <input type="hidden" name="resposta" id="resposta" value="">
                        <div class="col-md-8 m-auto">
                        
                            <span class="p-alternativa mb-2">
                                <input type="button" class="btn btn-responder ml-1 mr-3" value="a">
                            </span>
                            <span class="p-alternativa mb-2">
                                <input type="button" class="btn btn-responder ml-1 mr-3" value="b">
                            </span>
                            <span class="p-alternativa mb-2">
                                <input type="button" class="btn btn-responder ml-1 mr-3" value="c">
                            </span>
                            <span class="p-alternativa mb-2">
                                <input type="button" class="btn btn-responder ml-1 mr-3" value="d">
                            </span>
                            <button class="btn btn-outline-primary btn-sm ml-2 mt-4 btn-block" type="button" id="responder">Responder<i class="ml-2 fa fa-arrow-right"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="<?= BASE_URL . '/js/adicionar-dinheiro.js' ?>"></script>