<div class="container mt-5 p-3 mb-5">
    <div class="row">
        <div class="col p-3 text-center">
            <h3>Minhas compras</h3>
            <hr>
        </div>
    </div>
    <?php if(count($compras) != 0): ?>
        <div class="col-12 pt-5 pb-5">
            <table class="table table-striped table-hover">
                <div class="thead-dark">
                    <thead class="bg-dark text-light">
                        <tr>
                            <th>Produto</th>
                            <th>Vendedor</th>
                            <th>Data</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($compras as $compra): ?>
                            <tr>
                                <td><?= $compra['produto'] ?></td>
                                <td><?= $compra['vendedor'] ?></td>
                                <td><?= $compra['data_compra'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </div>
            </table>
        </div>
    <?php else: ?>
        <div class="col-12 text-center p-5 m-5">
            <hr>
            <h1>Nenhuma compra foi realizada</h1>
            <hr>
        </div>
    <?php endif; ?>
</div>