<div class="content mt-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-12 col-xl-12 com-sm-12 col-lg-12 contents">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-6 justify-content-center p-4">
                        <div class="mb-4 mt-4 float-center">
                            <h3 class="text-center mb-3 mt-3" style="font-weight: bolder;">Adicionar produto</h3>
                        </div>
                        <a class="btn btn-sm btn-outline-danger" href="<?= BASE_URL . '/produtos/meus' ?>"><i
                        class="fa fa-arrow-left mr-2"></i>Voltar</a>
                        <br>
                        <hr>
                        <div id="mensagem"></div>
                        <form method="POST" id="form-adicionar-produto" enctype="multipart/form-data">
                            <div class="col-md-12 m-auto">
                                <div class="form-group">
                                    <label for="img-produto">Imagem</label>
                                    <input type="file" name="img_produto" id="img-produto" class="form-control">
                                </div>
                            </div>

                            <div class="col-md-12 m-auto">
                                <div class="form-group">
                                    <label for="nome-produto">Nome</label>
                                    <input type="text" name="nome_produto" id="nome-produto" class="form-control"
                                        placeholder="Nome do produto">
                                    <div class="invalid-feedback text-center" id="nome-erro">

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 m-auto">
                                <div class="form-group">
                                    <label for="desc-produto">Descrição</label>
                                    <textarea class="form-control" name="desc_produto" id="desc-produto" cols="30"
                                        rows="2" placeholder="Descição do produto"></textarea>
                                    <div class="invalid-feedback text-center" id="desc-erro">

                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <label for="quantidade">Quantidade</label>
                                <div class="form-group">
                                    <input type="number" name="quant" id="quant" class="form-control"
                                        placeholder="Quantidade do produto">
                                    <div class="invalid-feedback text-center" id="quant-erro">

                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="preco">Preço (R$)</label>
                                    <input type="text" name="preco" id="preco" class="form-control" placeholder="Preço">
                                    <div class="invalid-feedback text-center" id="preco-erro">

                                    </div>
                                </div>
                            </div>
                            <div class="col-12 float-right">
                                <button type="submit" class="btn btn-block btn-sm btn-outline-primary"
                                id="btn-adicionar-produto"><i class="fa fa-plus mr-2"></i>Adicionar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script src="<?= BASE_URL . '/js/forms/form-adicionar-produto.js' ?>"></script>