<div class="col-sm-12 col-md-12 col-xl-8 col-lg-8 col-xs-12 m-auto pb-5 mt-5 mb-5">
    <div class="mt-5" style="background:#fff; border-radius: 20px;">
        <div class="card p-3" style="width: 100%;">
            <img class="img-fluid m-auto" src="<?= BASE_URL . '/files/produtos/'.$produto->foto?>"
                alt="${produto['nome_produto']}" style="max-width: 300px">
            <div class="caption text-center mt-1">
                <h4>${produto['nome_produto']}</h4>
                <!--  <small class="text-dark">${produto['descricao']}</small>  -->
                <p class="text-center text-success"><small><strong>${produto['quantidade']} Disponíveis</strong></small>
                </p>
            </div>
            <p><small><span class="text-dark" style="font-weight: bold;">Vendido por </span>&nbsp;<img width="28px"
                        class="rounded-circle"
                        src="http://127.0.0.1/web-store/files/usuarios/perfil/${produto['foto_vendedor']}"><strong><a
                            href="http://127.0.0.1/web-store/usuario/ver/${produto['id_usuario']}">&nbsp;${produto['vendedor']}</small></a></strong>
            </p>
            <div class="preco text-danger text-center">
                <h5>R$ ${produto['preco']}</h5>
            </div>
            <a class="btn btn-block btn-success text-center"
                href="http://127.0.0.1/web-store/produtos/comprar/${produto['id_produto']}">Comprar</a>
            <a class="btn btn-sm btn-block btn-outline-primary text-center"
                href="<?= BASE_URL . '/produtos' ?>"><i class="fa fa-arrow-left"></i>&nbsp;Voltar</a>
        </div>
    </div>
</div>