<style>
.card {
    /* border: none; */
    /* outline: none; */
    border-radius: 20px;
}
.card:hover {
    transform: translateY('-15px');
    transition: transform .3s;
    cursor: pointer;
}
.text {
    font-size: 13px;
}
.produto-div {
    border-radius: 20px;
}
.preco span {
    color: #fb3531;
    font-weight: bolder;
    font-size: 20px;
}
a:hover {
    text-decoration: none;
}
</style>
<div class="col-md-12 col-sm-12 col-xl-8 pt-5 pb-5 m-auto">
    <h2 class="text-center">Deseja realmente excluir esse produto?</h2>
    <div class="pb-3 pt-3 produto mt-3">
        <a href="<?= BASE_URL . '/produtos/meus' ?>" class="btn btn-sm btn-primary float-left"><i
                class="fa fa-arrow-left text-light mr-2"></i>Cancelar</a>
                <form action="<?=BASE_URL . '/produtos/excluir/'.$produto->id_produto ?>" method="POST">
                    <input type="text" name="confirm" id="" value="1" class="d-none">
                    <button type="submit" class="btn btn-sm btn-danger float-right"><i
                        class="fa fa-trash text-light mr-2"></i>Excluir</button>
                </form>
                <br>
    </div>
    <div class="card mt-3">
        <div class="produto-div align-items-center p-2 text-center">
            <img src="<?= BASE_URL .'/files/produtos/'.$produto->foto?>"
                class="img-fluid"  style="max-width: 300px; min-width: 240px;">
            <h5><?=$produto->nome_produto?></h5>
            <p><strong>Descrição: </strong><?=$produto->descricao?></p>
            Adicionado em: <strong><?=$produto->adicionado_em?></strong>
            <p><small class="text-success"><strong><?=$produto->quantidade .' '?>disponíveis no stock</strong></small></p>
            <div class="preco mt-3">
                <span class="text-dark">Preco:  <span class="text-danger">R$<?=$produto->preco?></span></span>
            </div>
        </div>
    </div>
</div>