<div class="container-fluid mt-5">
    <h3 class="text-center">Lista de produtos</h3>
    <hr>
    <div class="col-md-6 m-auto">
        <div class="form-group">
            <div class="input-group">
                <!-- <span class="input-group-text">Pesquisar por produto ou vendedor</span> -->
                <input type="text" name="pesquisa" id="pesquisar" class="form-control" placeholder="Pesquisar por produto ou vendedor">
            </div>
        </div>
    </div>
    <div class="row" id="row-produtos">
        <!-- produtos -->
    </div>
</div>
<script src="<?= BASE_URL . '/js/listar-produtos.js' ?>"></script>