<style>
.card {
    /* border: none; */
    /* outline: none; */
    border-radius: 20px;
}
.card:hover {
    transform: translateY('-15px');
    transition: transform .3s;
    cursor: pointer;
}
.text {
    font-size: 13px;
}
.produto-div {
    border-radius: 20px;
}
.preco span {
    color: #fb3531;
    font-weight: bolder;
    font-size: 20px;
}
a:hover {
    text-decoration: none;
}
</style>
<div class="container mb-5 mt-5 pb-2">
    <hr>
    <h3 class="text-center">Meus produtos</h3>
    <h5><a href="<?= BASE_URL . '/produtos/meus/adicionar' ?>" class=""><i class="fa fa-plus-square"></i> Adicionar produto</a></h5>
    <hr>
    <div class="row" id="row-produtos">
        <!-- meus produtos -->
    </div>
</div>
<script src="<?= BASE_URL . '/js/listar-produtos-by-user.js' ?>"></script>