<style>
.card {
    /* border: none; */
    outline: none;
    border-radius: 20px;
}
.card:hover {
    transform: translateY('-15px');
    transition: transform .3s;
    background-color: #e2e8ee;
    cursor: pointer;
}
.text {
    font-size: 13px;
}
.produto-div{
    background-color: rgba(0, 0, 0, .03);
}
.preco span {
    color: #fb3531;
    font-weight: bolder;
    font-size: 20px;
}
a:hover {
    text-decoration: none;
}
</style>
<div class="container mb-5 mt-5 pb-2">
    <hr>
    <h3 class="text-center">Meus produtos</h3>
    <h5><a href="meus/adicionar" class=""><i class="fa fa-plus-square"></i> Adicionar produto</a></h5>
    <hr>
    <div class="row">
    <?php foreach($produtos as $produto): ?>
        <div class="col-md-4 col-sm-6 col-xl-3">
            <div class="card mt-3">
                <div class="produto-div align-items-center p-2 text-center">
                    <img src="<?= BASE_URL . '/files/produtos/' . $produto['foto'] ?>" alt="<?= $produto['nome_produto'] ?>" class="rounded" width="160px">
                    <h5><?= $produto['nome_produto'] ?></h5>
                    <div class="mt-3 info">
                        <span class="text d-block"><?= $produto['descricao'] ?></span>
                    </div>
                    <div class="preco mt-3 text-dark">
                        <span>R$ <?= $produto['preco'] ?></span>
                    </div>
                </div>
                <div class="p-3 produto mt-3" style="background-color: #eee;">
                    <a href="<?= 'editar/'.$produto['id_produto'] ?>" class="btn btn-sm btn-primary float-left"><i class="fa fa-pencil text-light mr-2"></i>Editar</a>
                    <a href="<?= 'excluir/'.$produto['id_produto'] ?>" class="btn btn-sm btn-danger float-right"><i class="fa fa-trash text-light mr-2"></i>Excluir</a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</div>