<div class="container mt-5 p-3">
    <div class="row">
        <div class="col p-3 text-center">
            <h3>Minhas vendas</h3>
            <hr>
        </div>
    </div>
    <?php if(count($vendas) != 0): ?>
        <div class="col-12 pt-5 pb-5">
            <table class="table table-striped table-hover">
                <div class="thead-dark">
                    <thead class="bg-dark text-light">
                        <tr>
                            <th>Produto</th>
                            <th>Comprador</th>
                            <th>Data</th>
                        </tr>
                    </thead>
                    <tbody style="background-color: rgb(225, 225, 225); cursor: pointer">
                        <?php foreach($vendas as $venda): ?>
                            <tr>
                                <td><?= $venda['produto'] ?></td>
                                <td><?= $venda['comprador'] ?></td>
                                <td><?= $venda['data_compra'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </div>
            </table>
        </div>
    <?php else: ?>
        <div class="col-12 text-center p-5 m-5">
            <hr>
            <h1>Nenhuma venda foi realizada</h1>
            <hr>
        </div>
    <?php endif; ?>
</div>